swagger: "2.0"
info:
  description: "SwaggerとAPI Gatewayのサンプルです。"
  version: "1.0.0"
  title: "Swagger Sample"
#host: "petstore.swagger.io"
basePath: "/"
tags:
  - name: "Version"
schemes:
  - "https"
paths:
  /version:
    get:
      tags:
        - "Version"
      summary: "Pythonバージョン取得"
      description: "Lambdaで動いているPythonのバージョンを取得します。"
      operationId: "findPetsByStatus"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Version"
definitions:
  Version:
    type: "object"
    required:
      - "version"
    properties:
      version:
        type: "string"
        example: "3.6.2"