AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    SwaggerSample

    Sample SAM Template for SwaggerSample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
          - Label:
              default: General Configuration
            Parameters:
              - MyBucket
        ParameterLabels:
          MyBucket:
            default: hogehoge

Resources:
#    PythonVersionApi:
#        Type: AWS::Serverless::Api
#        Properties:
#            StageName: test
#            DefinitionBody:
#                Fn::Transform:
#                    Name: AWS::Include
#                    Parameters:
#                        Location: !sub s3://cm-fujii.genki-sam-test-bucket/swagger.yaml

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: hello_world/
            Handler: app.lambda_handler
            Runtime: python3.6
            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /version
                        Method: get
#                        RestApiId: !Ref PythonVersionApi

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/version"

#    HelloWorldFunction:
#      Description: "Hello World Lambda Function ARN"
#      Value: !GetAtt HelloWorldFunction.Arn

#    HelloWorldFunctionIamRole:
#      Description: "Implicit IAM Role created for Hello World function"
#      Value: !GetAtt HelloWorldFunctionRole.Arn
